import { getLocaleLetters } from '../i18n/localeRegistry';

// The default letter set used for English and as a baseline for tests.
export const ENGLISH_LETTERS = getLocaleLetters('en');
export const LETTERS = ENGLISH_LETTERS;

export const CATEGORIES = [
  'Animals',
  'Foods',
  'Countries',
  'Cities',
  'Movies',
  'TV Shows',
  'Sports',
  'Musical Instruments',
  'Types of Cars',
  'Things in a Kitchen',
  'Things at the Beach',
  'Clothing Items',
  'Famous People',
  'Fictional Characters',
  'Board Games',
  'Things That Are Cold',
  'Things That Are Hot',
  'Colors',
  'Fruits',
  'Vegetables',
  'Occupations / Jobs',
  'School Subjects',
  'Things in a Bedroom',
  'Things in a Bathroom',
  'Types of Shoes',
  'Books or Authors',
  'Candy / Sweets',
  'Drinks / Beverages',
  'Things You Do in the Morning',
  'Things You Find Outside',
  'Card Games',
  'Outdoor Activities',
  'Indoor Activities',
  'Restaurants / Fast Food Chains',
  'Superheroes',
  'Things That Make You Happy',
  'Things That Are Scary',
  'Dance Styles',
  'Types of Music Genres',
  'Hobbies',
  'Things with Wheels',
  'Things That Are Soft',
  'Tools',
  'Plants / Flowers',
  'Historical Figures',
  'Things in a Bag',
  'Things in Space',
  'Mythological Creatures',
  'Computer / Tech Terms',
  'Types of Weather',
  'Modes of Transport',
  'Things in an Office',
  'Pizza Toppings',
  'Types of Cheese',
  'Holidays / Celebrations',
  'Baby Items',
  "Words That Rhyme With 'Day'",
  'Things at a Party',
  'Things That Are Round',
  'Fairy Tale / Story Characters',
  "A Boy's Name",
  'U.S. Cities',
  'School Supplies',
  'Pro Sports Teams',
  'Insects',
  'Breakfast Foods',
  'Furniture',
  'T.V. Shows',
  'Things That Are Found in the Ocean',
  'Presidents',
  'Product Names',
  'Appliances',
  'Types of Drink',
  'Personality Traits',
  'Articles of Clothing',
  'Desserts',
  'Car Parts',
  'Things Found on a Map',
  'Athletes',
  '4-Letter Words',
  'Items in a Refrigerator',
  'Farm Animals',
  'Street Names',
  'Things on a Beach',
  "A Girl's Name",
  'Villains/Monsters',
  'Footwear',
  "Something You're Afraid Of",
  'Terms of Measurement',
  'Book Titles',
  'Heroes',
  'Gifts/Presents',
  'Kinds of Dances',
  'Things That Are Black',
  'Vehicles',
  'Tropical Locations',
  'College Majors',
  'Dairy Products',
  'Things in a Souvenir Shop',
  'Items in Your Purse/Wallet',
  'Famous Females',
  'Medicine/Drugs',
  'Things Made of Metal',
  'People in Uniform',
  'Things You Plug In',
  'Languages',
  'Names Used in the Bible',
  'Junk Food',
  'Things That Grow',
  'Companies',
  'Video Games',
  'Electronic Gadgets',
  'Things That Use a Remote',
  'Internet Lingo',
  'Offensive Words',
  'Wireless Things',
  'Computer Parts',
  'Software',
  'Websites',
  'Game Terms',
  'Things in a Grocery Store',
  'Reasons to Quit Your Job',
  'Things That Have Stripes',
  'Tourist Attractions',
  'Diet Foods',
  'Things Found in a Hospital',
  'Food/Drink That Is Green',
  'Weekend Activities',
  'Acronyms',
  'Seafood',
  'Christmas Songs',
  'Words Ending in -N',
  'Words With Double Letters',
  'Childrens Books',
  'Things Found at a Bar',
  'Sports Played Indoors',
  'Names Used in Songs',
  'Foods You Eat Raw',
  'Places in Europe',
  'Olympic Events',
  'Things You See at the Zoo',
  'Math Terms',
  'Animals in Books or Movies',
  'Things to Do at a Party',
  'Sandwiches',
  'Items in a Catalog',
  'World Leaders/Politicians',
  'Excuses for Being Late',
  'Ice Cream Flavors',
  'Things That Jump/Bounce',
  'Television Stars',
  'Things in a Park',
  'Foreign Cities',
  'Stones/Gems',
  'Nicknames',
  'Things in the Sky',
  'Colleges/Universities',
  'Fish',
  'Things That Have Spots',
  'Terms of Endearment',
  'Items in This Room',
  'Menu Items',
  'Magazines',
  'Capitals',
  'Kinds of Candy',
  'Items You Save Up to Buy',
  'Footware',
  'Something You Keep Hidden',
  'Items in a Suitcase',
  'Things With Tails',
  'Sports Equipment',
  'Crimes',
  'Things That Are Sticky',
  'Awards/Ceremonies',
  'Cars',
  'Spices/Herbs',
  'Bad Habits',
  'Cosmetics/Toiletries',
  'Celebrities',
  'Cooking Utensils',
  'Reptiles/Amphibians',
  'Parks',
  'Leisure Activities',
  "Things You're Allergic To",
  'Restaurants',
  'Notorious People',
  'Things in a Medicine Cabinet',
  'Toys',
  'Household Chores',
  'Bodies of Water',
  'Authors',
  'Halloween Costumes',
  'Weapons',
  'Words Associated With Exercise',
  'Song Titles',
  'Parts of the Body',
  'Ethnic Foods',
  'Things You Shout',
  'Birds',
  'Methods of Transportation',
  'Items in a Kitchen',
  'Flowers',
  'Things You Replace',
  'Famous Duos and Trios',
  'Things Found in a Desk',
  'Vacation Spots',
  'Diseases',
  'Words Associated With Money',
  'Items in a Vending Machine',
  'Movie Titles',
  'Games',
  'Things That You Wear',
  'Beers',
  'Things at a Circus',
  'States',
  'Things You Throw Away',
  'Occupations',
  'Cartoon Characters',
  'Types of Drinks',
  'Musical Groups',
  'Store Names',
  'Things at a Football Game',
  'Trees',
  'Kinds of Soup',
  'Things Found in New York',
  'Things You Get Tickets For',
  'Things You Do at Work',
  'Foreign Words Used in English',
  "Things You Shouldn't Touch",
  'Spicy Foods',
  'Things at a Carnival',
  'Things You Make',
  'Places to Hang Out',
  'Computer Programs',
  'Honeymoon Spots',
  'Things You Buy for Kids',
  'Things That Can Kill You',
  'Reasons to Take Out a Loan',
  'Words Associated With Winter',
  'Things to Do on a Date',
  'Historic Events',
  'Things You Store Items In',
  'Things You Do Every Day',
  'Things You Get in the Mail',
  'Things You Save Up to Buy',
  'Things You Sit In/On',
  'Reasons to Make a Phone Call',
  'Titles People Can Have',
  'Things That Have Buttons',
  'Items You Take on a Trip',
  'Things That Have Wheels',
  'Reasons to Call 911',
  'Things That Make You Smile',
  'Ways to Kill Time',
  'Things That Can Get You Fired',
  'Holiday Activities',
];

export const BUFFER_SECONDS = 5;

// Settings bounds and defaults
export const DURATION_MIN = 10;
export const DURATION_MAX = 600;
export const DURATION_DEFAULT = 90;

export const CAT_COUNT_MIN = 1;
export const CAT_COUNT_MAX = 25;
export const CAT_COUNT_DEFAULT = 12;

export const ROUNDS_MIN = 1;
export const ROUNDS_MAX = 10;
export const ROUNDS_DEFAULT = 3;
