/* The canonical built-in category keys. This list — not the English translation
 * file — is the source of truth: categories.*.json translate these keys, and
 * completeness.test.ts asserts the English file matches this list exactly. */
const CATEGORY_KEYS: readonly string[] = Object.freeze([
  "Animals",
  "Foods",
  "Countries",
  "Cities",
  "Movies",
  "TV Shows",
  "Sports",
  "Instruments",
  "Types of Cars",
  "Kitchen Things",
  "Beach Things",
  "Clothing Items",
  "Famous People",
  "Fictional Characters",
  "Board Games",
  "Cold Things",
  "Hot Things",
  "Colors",
  "Fruits",
  "Vegetables",
  "School Subjects",
  "Bedroom Things",
  "Bathroom Things",
  "Candy / Sweets",
  "Beverages",
  "Morning Habits",
  "Outdoor Things",
  "Card Games",
  "Outdoor Activities",
  "Indoor Activities",
  "Fast Food Chains",
  "Superheroes",
  "Happy Things",
  "Scary Things",
  "Dance Styles",
  "Music Genres",
  "Hobbies",
  "Things with Wheels",
  "Soft Things",
  "Tools",
  "Plants & Flowers",
  "Historical Figures",
  "Things in a Bag",
  "Things in Space",
  "Mythical Beasts",
  "Tech Terms",
  "Weather Types",
  "Modes of Transport",
  "Office Things",
  "Pizza Toppings",
  "Types of Cheese",
  "Celebrations",
  "Baby Items",
  "Rhymes With 'Day'",
  "Party Things",
  "Round Things",
  "Fairy Tale Figures",
  "A Boy's Name",
  "U.S. Cities",
  "School Supplies",
  "Sports Teams",
  "Insects",
  "Breakfast Foods",
  "Furniture",
  "Ocean Things",
  "Presidents",
  "Product Names",
  "Appliances",
  "Personality Traits",
  "Desserts",
  "Car Parts",
  "Map Features",
  "Athletes",
  "4-Letter Words",
  "Fridge Items",
  "Farm Animals",
  "Street Names",
  "A Girl's Name",
  "Villains/Monsters",
  "Footwear",
  "Fears",
  "Measurements",
  "Book Titles",
  "Heroes",
  "Gifts/Presents",
  "Black Things",
  "Vehicles",
  "Tropical Places",
  "College Majors",
  "Dairy Products",
  "Souvenirs",
  "Wallet Items",
  "Famous Women",
  "Medicine/Drugs",
  "Metal Things",
  "People in Uniform",
  "Things You Plug In",
  "Languages",
  "Bible Names",
  "Junk Food",
  "Growing Things",
  "Companies",
  "Video Games",
  "Gadgets",
  "Things With Remotes",
  "Internet Lingo",
  "Offensive Words",
  "Wireless Things",
  "Computer Parts",
  "Software",
  "Websites",
  "Game Terms",
  "Grocery Items",
  "Reasons to Quit",
  "Striped Things",
  "Tourist Attractions",
  "Diet Foods",
  "Hospital Things",
  "Green Foods",
  "Weekend Activities",
  "Acronyms",
  "Seafood",
  "Christmas Songs",
  "Words Ending in -N",
  "Double-Letter Words",
  "Children's Books",
  "Bar Things",
  "Indoor Sports",
  "Names in Songs",
  "Raw Foods",
  "European Places",
  "Olympic Events",
  "Things at the Zoo",
  "Math Terms",
  "Famous Animals",
  "Party Activities",
  "Sandwiches",
  "Catalog Items",
  "World Leaders",
  "Excuses to Be Late",
  "Ice Cream Flavors",
  "Bouncy Things",
  "TV Stars",
  "Park Things",
  "Foreign Cities",
  "Stones/Gems",
  "Nicknames",
  "Things in the Sky",
  "Universities",
  "Fish",
  "Spotted Things",
  "Terms of Endearment",
  "Items in This Room",
  "Menu Items",
  "Magazines",
  "Capitals",
  "Big Purchases",
  "Hidden Things",
  "Suitcase Items",
  "Things With Tails",
  "Sports Gear",
  "Crimes",
  "Sticky Things",
  "Awards",
  "Spices/Herbs",
  "Bad Habits",
  "Cosmetics",
  "Celebrities",
  "Utensils",
  "Reptiles/Amphibians",
  "Parks",
  "Allergies",
  "Restaurants",
  "Infamous People",
  "Medicine Cabinet",
  "Toys",
  "Chores",
  "Bodies of Water",
  "Authors",
  "Halloween Costumes",
  "Weapons",
  "Exercise Words",
  "Song Titles",
  "Body Parts",
  "Ethnic Foods",
  "Things You Shout",
  "Birds",
  "Flowers",
  "Things You Replace",
  "Duos & Trios",
  "Desk Items",
  "Vacation Spots",
  "Diseases",
  "Money Words",
  "Vending Items",
  "Beers",
  "Circus Things",
  "States",
  "Throwaway Things",
  "Occupations",
  "Cartoon Characters",
  "Musical Groups",
  "Store Names",
  "Stadium Things",
  "Trees",
  "Kinds of Soup",
  "New York Things",
  "Reasons for Tickets",
  "Work Tasks",
  "Borrowed Words",
  "Untouchable Things",
  "Spicy Foods",
  "Carnival Things",
  "Things You Make",
  "Hangout Spots",
  "Honeymoon Spots",
  "Things for Kids",
  "Deadly Things",
  "Reasons for a Loan",
  "Winter Words",
  "Date Ideas",
  "Historic Events",
  "Containers",
  "Daily Habits",
  "Mail Items",
  "Things to Sit On",
  "Reasons to Call",
  "Titles for People",
  "Things With Buttons",
  "Travel Items",
  "Reasons to Call 911",
  "Time Killers",
  "Fireable Offenses",
  "Holiday Activities",
]);

export { CATEGORY_KEYS };
